name: Test

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.21, 1.22, 1.23, 1.24]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go get

      - name: Run tests
        run: go test ./...
